---
name: Lint Code Base

on:
  pull_request: {}
  push:
    branches-ignore:
    - 'master'

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Super-Linter
        uses: github/super-linter@v2.1.0
